import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]
[window]

opacity = 0.6

[shell]

program = "/usr/bin/fish"

[font]

normal.family = "Source Code Pro"
bold.family = "Source Code Pro"
italic.family ="Source Code Pro"
bold_italic.family = "Source Code Pro"

size = 9.0

[env]
TERM = "xterm-256color"
